import type { ProGenerationResult } from "./types";

/**
 * Generate a PDF from Pro results using jsPDF.
 * Uses a clean, professional layout.
 */
export async function generatePDF(result: ProGenerationResult): Promise<Blob> {
  const { jsPDF } = await import("jspdf");

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Helper functions
  const checkPageBreak = (neededSpace: number) => {
    const pageHeight = doc.internal.pageSize.getHeight();
    if (y + neededSpace > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const addSectionHeader = (title: string) => {
    checkPageBreak(15);
    y += 5;
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 64, 175); // Blue
    doc.text(title, margin, y);
    y += 2;
    doc.setDrawColor(30, 64, 175);
    doc.setLineWidth(0.5);
    doc.line(margin, y, margin + contentWidth, y);
    y += 6;
  };

  const addWrappedText = (text: string, fontSize: number = 10, isBold: boolean = false) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    doc.setTextColor(31, 41, 55); // Gray-800

    const lines = doc.splitTextToSize(text, contentWidth);
    for (const line of lines) {
      checkPageBreak(5);
      doc.text(line, margin, y);
      y += fontSize * 0.4 + 1;
    }
    y += 2;
  };

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(17, 24, 39);
  doc.text("Resume Tailor Pro Report", margin, y);
  y += 10;

  // Summary
  addSectionHeader("Executive Summary");
  addWrappedText(result.summary);

  // Tailored Resume
  addSectionHeader("Tailored Resume");
  const resumeLines = result.tailoredResume.split("\n");
  for (const line of resumeLines) {
    if (!line.trim()) {
      y += 3;
      continue;
    }
    // Detect section headers in resume
    if (line === line.toUpperCase() && line.length > 2 && line.length < 40) {
      addWrappedText(line, 11, true);
    } else if (line.startsWith("  -") || line.startsWith("  *")) {
      const bullet = line.replace(/^\s*[-*]\s*/, "");
      checkPageBreak(5);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(55, 65, 81);
      const bulletLines = doc.splitTextToSize(`   ${bullet}`, contentWidth - 5);
      for (let i = 0; i < bulletLines.length; i++) {
        checkPageBreak(4);
        if (i === 0) {
          doc.text("\u2022", margin + 2, y);
        }
        doc.text(bulletLines[i], margin + 6, y);
        y += 4;
      }
    } else {
      addWrappedText(line, 10);
    }
  }

  // Cover Letter
  addSectionHeader("Cover Letter");
  const coverParagraphs = result.coverLetter.split("\n\n");
  for (const paragraph of coverParagraphs) {
    if (paragraph.trim()) {
      addWrappedText(paragraph.trim());
      y += 2;
    }
  }

  // Skills Section
  if (result.skillsSectionRewrite) {
    addSectionHeader("Skills Section (Recommended)");
    addWrappedText(result.skillsSectionRewrite);
  }

  // Keyword Checklist
  if (result.keywordChecklist.length > 0) {
    addSectionHeader("Keyword Checklist");
    for (const item of result.keywordChecklist) {
      checkPageBreak(5);
      const prefix = item.found ? "[FOUND]" : "[MISSING]";
      doc.setFontSize(9);
      doc.setFont("helvetica", item.found ? "normal" : "bold");
      doc.setTextColor(item.found ? 22 : 185, item.found ? 163 : 28, item.found ? 74 : 28);
      doc.text(`${prefix} ${item.keyword}`, margin, y);
      if (item.suggestion) {
        doc.setFont("helvetica", "normal");
        doc.setTextColor(107, 114, 128);
        doc.text(` - ${item.suggestion}`, margin + 60, y);
      }
      y += 4.5;
    }
  }

  // Next Actions
  if (result.nextActions.length > 0) {
    addSectionHeader("Next Actions");
    result.nextActions.forEach((action, i) => {
      addWrappedText(`${i + 1}. ${action}`, 10);
    });
  }

  // Footer on each page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(156, 163, 175);
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.text(
      `Generated by Resume Tailor | Page ${i} of ${totalPages}`,
      margin,
      pageHeight - 10
    );
  }

  return doc.output("blob");
}
