/**
 * Shared PDF rendering primitives and document renderers.
 * Used by both client (export-pdf.ts) and server (export-pdf-server.ts).
 */

import type { jsPDF } from "jspdf";
import type { ProDocument, DocResume } from "./pro-document";
import type { ProOutput } from "./schema";
import { proOutputToDocument } from "./pro-document";

// ── PDF Context ──

export interface PdfContext {
  pdf: jsPDF;
  y: number;
  margin: number;
  contentWidth: number;
  pageHeight: () => number;
}

export function createPdfContext(pdf: jsPDF): PdfContext {
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  return { pdf, y: margin, margin, contentWidth, pageHeight: () => pdf.internal.pageSize.getHeight() };
}

// ── Primitives ──

export function checkPageBreak(ctx: PdfContext, needed: number) {
  if (ctx.y + needed > ctx.pageHeight() - ctx.margin) {
    ctx.pdf.addPage();
    ctx.y = ctx.margin;
  }
}

export function addSectionHeader(ctx: PdfContext, title: string) {
  checkPageBreak(ctx, 12);
  ctx.y += 4;
  ctx.pdf.setFontSize(10);
  ctx.pdf.setFont("helvetica", "bold");
  ctx.pdf.setTextColor(107, 114, 128);
  ctx.pdf.text(title.toUpperCase(), ctx.margin, ctx.y);
  ctx.y += 1.5;
  ctx.pdf.setDrawColor(209, 213, 219);
  ctx.pdf.setLineWidth(0.3);
  ctx.pdf.line(ctx.margin, ctx.y, ctx.margin + ctx.contentWidth, ctx.y);
  ctx.y += 5;
}

export function addWrappedText(
  ctx: PdfContext,
  text: string,
  fontSize = 10,
  bold = false,
  color: [number, number, number] = [55, 65, 81],
) {
  ctx.pdf.setFontSize(fontSize);
  ctx.pdf.setFont("helvetica", bold ? "bold" : "normal");
  ctx.pdf.setTextColor(...color);
  const lines = ctx.pdf.splitTextToSize(text, ctx.contentWidth);
  for (const line of lines) {
    checkPageBreak(ctx, fontSize * 0.4 + 1);
    ctx.pdf.text(line, ctx.margin, ctx.y);
    ctx.y += fontSize * 0.4 + 1;
  }
  ctx.y += 1.5;
}

export function addBullet(ctx: PdfContext, text: string) {
  ctx.pdf.setFontSize(9.5);
  ctx.pdf.setFont("helvetica", "normal");
  ctx.pdf.setTextColor(55, 65, 81);
  const lines = ctx.pdf.splitTextToSize(text, ctx.contentWidth - 7);
  for (let i = 0; i < lines.length; i++) {
    checkPageBreak(ctx, 4);
    if (i === 0) {
      ctx.pdf.circle(ctx.margin + 2.5, ctx.y - 1, 0.5, "F");
    }
    ctx.pdf.text(lines[i], ctx.margin + 6, ctx.y);
    ctx.y += 3.8;
  }
}

export function addFooter(ctx: PdfContext) {
  const totalPages = ctx.pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    ctx.pdf.setPage(i);
    ctx.pdf.setFontSize(7);
    ctx.pdf.setFont("helvetica", "normal");
    ctx.pdf.setTextColor(156, 163, 175);
    ctx.pdf.text(
      `Generated by ResumeMate AI  |  Page ${i} of ${totalPages}`,
      ctx.margin,
      ctx.pageHeight() - 8,
    );
  }
}

// ── Experience helper ──

function renderExperience(ctx: PdfContext, resume: DocResume) {
  for (let i = 0; i < resume.experience.length; i++) {
    const exp = resume.experience[i];
    if (i > 0) ctx.y += 2;
    checkPageBreak(ctx, 12);

    ctx.pdf.setFontSize(10);
    ctx.pdf.setFont("helvetica", "bold");
    ctx.pdf.setTextColor(17, 24, 39);
    ctx.pdf.text(exp.company, ctx.margin, ctx.y);
    if (exp.location) {
      ctx.pdf.setFontSize(8.5);
      ctx.pdf.setTextColor(107, 114, 128);
      const locWidth = ctx.pdf.getTextWidth(exp.location);
      ctx.pdf.text(exp.location, ctx.margin + ctx.contentWidth - locWidth, ctx.y);
    }
    ctx.y += 4;

    ctx.pdf.setFontSize(9.5);
    ctx.pdf.setFont("helvetica", "normal");
    ctx.pdf.setTextColor(55, 65, 81);
    ctx.pdf.text(exp.title, ctx.margin, ctx.y);
    const dateParts = [exp.start, exp.end].filter(Boolean).join(" \u2013 ");
    if (dateParts) {
      ctx.pdf.setFontSize(8.5);
      ctx.pdf.setTextColor(107, 114, 128);
      const dateWidth = ctx.pdf.getTextWidth(dateParts);
      ctx.pdf.text(dateParts, ctx.margin + ctx.contentWidth - dateWidth, ctx.y);
    }
    ctx.y += 4;

    for (const b of exp.bullets) addBullet(ctx, b);

    if (exp.tech && exp.tech.length > 0) {
      ctx.pdf.setFontSize(8);
      ctx.pdf.setTextColor(107, 114, 128);
      ctx.pdf.text(`Tech: ${exp.tech.join(", ")}`, ctx.margin + 6, ctx.y);
      ctx.y += 4;
    }
  }
  ctx.y += 2;
}

// ── Resume Renderer ──

export async function renderResumePdf(proDoc: ProDocument): Promise<jsPDF> {
  const { jsPDF: JsPDF } = await import("jspdf");
  const pdf = new JsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const ctx = createPdfContext(pdf);
  const r = proDoc.resume;

  // Header
  pdf.setFontSize(22);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(17, 24, 39);
  pdf.text(r.name, ctx.margin, ctx.y);
  ctx.y += 7;

  if (r.headline) {
    addWrappedText(ctx, r.headline, 11, false, [107, 114, 128]);
  }

  // Contact row
  const contactParts: string[] = [];
  if (r.email) contactParts.push(r.email);
  if (r.phone) contactParts.push(r.phone);
  if (r.location) contactParts.push(r.location);
  if (r.links) contactParts.push(...r.links);
  if (contactParts.length > 0) {
    pdf.setFontSize(8.5);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(107, 114, 128);
    pdf.text(contactParts.join("  |  "), ctx.margin, ctx.y);
    ctx.y += 5;
  }

  // Professional Summary
  if (r.summary) {
    addSectionHeader(ctx, "Professional Summary");
    addWrappedText(ctx, r.summary, 10);
  }

  // Experience
  if (r.experience.length > 0) {
    addSectionHeader(ctx, "Experience");
    renderExperience(ctx, r);
  }

  // Skills
  if (r.skills.groups.length > 0) {
    addSectionHeader(ctx, "Skills");
    for (const g of r.skills.groups) {
      checkPageBreak(ctx, 6);
      pdf.setFontSize(9.5);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(17, 24, 39);
      pdf.text(`${g.label}: `, ctx.margin, ctx.y);
      const labelWidth = pdf.getTextWidth(`${g.label}: `);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(55, 65, 81);
      const skillLines = pdf.splitTextToSize(g.items.join(" \u2022 "), ctx.contentWidth - labelWidth);
      pdf.text(skillLines[0], ctx.margin + labelWidth, ctx.y);
      ctx.y += 4;
      for (let i = 1; i < skillLines.length; i++) {
        pdf.text(skillLines[i], ctx.margin, ctx.y);
        ctx.y += 4;
      }
    }
    ctx.y += 2;
  }

  // Projects
  if (r.projects && r.projects.length > 0) {
    addSectionHeader(ctx, "Projects");
    for (const p of r.projects) {
      checkPageBreak(ctx, 8);
      addWrappedText(ctx, p.name, 9.5, true, [17, 24, 39]);
      for (const b of p.bullets) addBullet(ctx, b);
      if (p.tech && p.tech.length > 0) {
        pdf.setFontSize(8);
        pdf.setTextColor(107, 114, 128);
        pdf.text(`Tech: ${p.tech.join(", ")}`, ctx.margin + 6, ctx.y);
        ctx.y += 4;
      }
      ctx.y += 1;
    }
  }

  // Education
  if (r.education && r.education.length > 0) {
    addSectionHeader(ctx, "Education");
    for (const edu of r.education) {
      checkPageBreak(ctx, 6);
      pdf.setFontSize(9.5);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(17, 24, 39);
      const eduLine = edu.degree ? `${edu.school} \u2014 ${edu.degree}` : edu.school;
      pdf.text(eduLine, ctx.margin, ctx.y);
      const dateLine = [edu.start, edu.end].filter(Boolean).join(" \u2013 ");
      if (dateLine) {
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(107, 114, 128);
        pdf.setFontSize(8.5);
        const dateWidth = pdf.getTextWidth(dateLine);
        pdf.text(dateLine, ctx.margin + ctx.contentWidth - dateWidth, ctx.y);
      }
      ctx.y += 4.5;
    }
    ctx.y += 2;
  }

  // Certifications
  if (r.certifications && r.certifications.length > 0) {
    addSectionHeader(ctx, "Certifications");
    addWrappedText(ctx, r.certifications.join(" \u2022 "), 9.5);
  }

  addFooter(ctx);
  return pdf;
}

// ── Cover Letter Renderer ──

export async function renderCoverLetterPdf(proDoc: ProDocument): Promise<jsPDF> {
  const { jsPDF: JsPDF } = await import("jspdf");
  const pdf = new JsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const ctx = createPdfContext(pdf);
  const cl = proDoc.coverLetter;

  // Date
  addWrappedText(ctx, cl.date, 10, false, [107, 114, 128]);
  ctx.y += 3;

  // Recipient
  if (cl.recipientLine) {
    addWrappedText(ctx, `Dear ${cl.recipientLine},`, 10, false, [31, 41, 55]);
  }
  if (cl.company || cl.role) {
    const reLine = [cl.role && `Re: ${cl.role}`, cl.company].filter(Boolean).join(" at ");
    addWrappedText(ctx, reLine, 9.5, false, [107, 114, 128]);
  }
  ctx.y += 2;

  // Body
  for (const paragraph of cl.paragraphs) {
    addWrappedText(ctx, paragraph, 10);
    ctx.y += 2;
  }

  // Closing
  ctx.y += 4;
  addWrappedText(ctx, cl.closing || "Sincerely,", 10);
  ctx.y += 3;
  addWrappedText(ctx, cl.signatureName || proDoc.resume.name, 10, true, [17, 24, 39]);

  addFooter(ctx);
  return pdf;
}

// ── Insights Renderer ──

export async function renderInsightsPdf(result: ProOutput): Promise<jsPDF> {
  const { jsPDF: JsPDF } = await import("jspdf");
  const pdf = new JsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const ctx = createPdfContext(pdf);

  // Header
  pdf.setFontSize(22);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(17, 24, 39);
  pdf.text("Improvement Insights", ctx.margin, ctx.y);
  ctx.y += 7;

  // Candidate name + date
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(107, 114, 128);
  const dateLine = `${result.tailoredResume.name}  |  ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`;
  pdf.text(dateLine, ctx.margin, ctx.y);
  ctx.y += 8;

  // 1. Keyword Checklist
  if (result.keywordChecklist.length > 0) {
    addSectionHeader(ctx, "Keyword Checklist");
    for (const kw of result.keywordChecklist) {
      checkPageBreak(ctx, 5);
      const icon = kw.found ? "\u2713" : "\u2717";
      const color: [number, number, number] = kw.found ? [22, 163, 74] : [220, 38, 38];
      pdf.setFontSize(9.5);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...color);
      pdf.text(icon, ctx.margin, ctx.y);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(55, 65, 81);
      pdf.text(kw.keyword, ctx.margin + 6, ctx.y);
      if (kw.suggestion) {
        pdf.setFontSize(8.5);
        pdf.setTextColor(107, 114, 128);
        const suggLines = pdf.splitTextToSize(`\u2192 ${kw.suggestion}`, ctx.contentWidth - 10);
        ctx.y += 4;
        for (const line of suggLines) {
          checkPageBreak(ctx, 4);
          pdf.text(line, ctx.margin + 6, ctx.y);
          ctx.y += 3.5;
        }
      } else {
        ctx.y += 4.5;
      }
    }
    ctx.y += 2;
  }

  // 2. Recruiter Feedback
  if (result.recruiterFeedback.length > 0) {
    addSectionHeader(ctx, "Recruiter Feedback");
    result.recruiterFeedback.forEach((item, i) => {
      checkPageBreak(ctx, 6);
      pdf.setFontSize(9.5);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(37, 99, 235);
      pdf.text(`${i + 1}.`, ctx.margin, ctx.y);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(55, 65, 81);
      const lines = pdf.splitTextToSize(item, ctx.contentWidth - 8);
      for (let j = 0; j < lines.length; j++) {
        checkPageBreak(ctx, 4);
        pdf.text(lines[j], ctx.margin + 7, ctx.y);
        ctx.y += 4;
      }
      ctx.y += 1;
    });
    ctx.y += 2;
  }

  // 3. Bullet Rewrites
  if (result.bulletRewrites.length > 0) {
    addSectionHeader(ctx, "Bullet Rewrites");
    for (const rw of result.bulletRewrites) {
      checkPageBreak(ctx, 20);

      // Section label
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(107, 114, 128);
      pdf.text(rw.section, ctx.margin, ctx.y);
      ctx.y += 4;

      // Before
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(220, 38, 38);
      pdf.text("BEFORE:", ctx.margin, ctx.y);
      ctx.y += 3.5;
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(107, 114, 128);
      const beforeLines = pdf.splitTextToSize(rw.original || "(new bullet)", ctx.contentWidth - 4);
      for (const line of beforeLines) {
        checkPageBreak(ctx, 4);
        pdf.text(line, ctx.margin + 2, ctx.y);
        ctx.y += 3.5;
      }
      ctx.y += 1;

      // After
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(22, 163, 74);
      pdf.text("AFTER:", ctx.margin, ctx.y);
      ctx.y += 3.5;
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(17, 24, 39);
      const afterLines = pdf.splitTextToSize(rw.rewritten, ctx.contentWidth - 4);
      for (const line of afterLines) {
        checkPageBreak(ctx, 4);
        pdf.text(line, ctx.margin + 2, ctx.y);
        ctx.y += 3.5;
      }
      ctx.y += 1;

      // Notes
      if (rw.notes) {
        pdf.setFontSize(8.5);
        pdf.setTextColor(37, 99, 235);
        const noteLines = pdf.splitTextToSize(rw.notes, ctx.contentWidth - 4);
        for (const line of noteLines) {
          checkPageBreak(ctx, 4);
          pdf.text(line, ctx.margin + 2, ctx.y);
          ctx.y += 3.5;
        }
      }
      ctx.y += 3;
    }
  }

  // 4. Experience Gaps
  if (result.experienceGaps.length > 0) {
    addSectionHeader(ctx, "Experience Gaps");
    for (const gap of result.experienceGaps) {
      checkPageBreak(ctx, 10);

      // Severity badge
      const sevColor: [number, number, number] =
        gap.severity === "high" ? [220, 38, 38] :
        gap.severity === "medium" ? [202, 138, 4] :
        [107, 114, 128];

      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...sevColor);
      pdf.text(`[${gap.severity.toUpperCase()}]`, ctx.margin, ctx.y);
      const badgeWidth = pdf.getTextWidth(`[${gap.severity.toUpperCase()}] `);

      pdf.setFontSize(9.5);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(17, 24, 39);
      const gapLines = pdf.splitTextToSize(gap.gap, ctx.contentWidth - badgeWidth - 2);
      pdf.text(gapLines[0], ctx.margin + badgeWidth, ctx.y);
      ctx.y += 4;
      for (let j = 1; j < gapLines.length; j++) {
        checkPageBreak(ctx, 4);
        pdf.text(gapLines[j], ctx.margin, ctx.y);
        ctx.y += 4;
      }

      // Suggestion
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(55, 65, 81);
      const suggLines = pdf.splitTextToSize(gap.suggestion, ctx.contentWidth - 4);
      for (const line of suggLines) {
        checkPageBreak(ctx, 4);
        pdf.text(line, ctx.margin + 2, ctx.y);
        ctx.y += 3.8;
      }
      ctx.y += 3;
    }
  }

  // 5. Next Actions
  if (result.nextActions.length > 0) {
    addSectionHeader(ctx, "Next Actions");
    result.nextActions.forEach((action, i) => {
      checkPageBreak(ctx, 6);
      pdf.setFontSize(9.5);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(37, 99, 235);
      pdf.text(`${i + 1}.`, ctx.margin, ctx.y);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(55, 65, 81);
      const lines = pdf.splitTextToSize(action, ctx.contentWidth - 8);
      for (let j = 0; j < lines.length; j++) {
        checkPageBreak(ctx, 4);
        pdf.text(lines[j], ctx.margin + 7, ctx.y);
        ctx.y += 4;
      }
      ctx.y += 1;
    });
  }

  addFooter(ctx);
  return pdf;
}
