import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "ResumeMate AI terms of service. Usage terms, limitations, and acceptable use.",
};

export default function TermsPage() {
  return (
    <div className="px-4 py-16">
      <div className="prose mx-auto max-w-3xl">
        <h1 className="text-3xl font-bold text-gray-900">Terms of Service</h1>
        <p className="mt-2 text-sm text-gray-500">Last updated: February 2026</p>

        <div className="mt-8 space-y-8 text-sm text-gray-700">
          <section>
            <h2 className="text-lg font-semibold text-gray-900">Service description</h2>
            <p className="mt-2">
              ResumeMate AI provides automated resume analysis and optimization suggestions. The service compares your resume against a job description to identify keyword gaps, formatting issues, and improvement opportunities.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">No guarantees</h2>
            <p className="mt-2">
              ResumeMate AI provides general guidance only. We do not guarantee that using our service will result in job interviews, job offers, or employment. Results are generated by AI and may contain inaccuracies. You should review all suggestions carefully and use your own judgment before applying changes to your resume.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">Limitation of liability</h2>
            <p className="mt-2">
              To the maximum extent permitted by law, ResumeMate AI and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">Acceptable use</h2>
            <p className="mt-2">You agree not to:</p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>Use the service to generate false or misleading resume content</li>
              <li>Fabricate work experience, credentials, or achievements based on suggestions</li>
              <li>Use automated tools to make bulk requests to our service</li>
              <li>Attempt to reverse-engineer our analysis methodology</li>
              <li>Resell or redistribute analysis results as a service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">Payments and refunds</h2>
            <p className="mt-2">
              The Full Tailor Pack is a one-time payment processed through Stripe. Due to the instant-delivery nature of digital analysis results, refunds are handled on a case-by-case basis. Contact support@resumemate.ai for refund requests.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">Privacy</h2>
            <p className="mt-2">
              Your use of ResumeMate AI is also governed by our <a href="/privacy" className="text-primary hover:underline">Privacy Policy</a>. We never store your resume or job description content. See the Privacy Policy for full details on data handling.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">Changes to terms</h2>
            <p className="mt-2">
              We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">Contact</h2>
            <p className="mt-2">
              Questions about these terms? Contact us at legal@resumemate.ai.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
