import { NextResponse } from "next/server";
import { rateLimitRoute } from "@/lib/rate-limiter";

export async function POST(request: Request) {
  try {
    // Rate limit
    const { response: rateLimited } = rateLimitRoute(request, "email-pro");
    if (rateLimited) return rateLimited;

    if (!process.env.RESEND_API_KEY) {
      return NextResponse.json(
        { error: "Email delivery is not configured.", disabled: true },
        { status: 503 }
      );
    }

    const body = await request.json();
    const { email, reportText } = body;

    if (!email || typeof email !== "string" || !email.includes("@")) {
      return NextResponse.json({ error: "Valid email is required." }, { status: 400 });
    }

    if (!reportText || typeof reportText !== "string") {
      return NextResponse.json({ error: "Report content is required." }, { status: 400 });
    }

    // Dynamic import to avoid issues if resend isn't installed
    const { Resend } = await import("resend");
    const resend = new Resend(process.env.RESEND_API_KEY);

    const { error } = await resend.emails.send({
      from: "ResumeMate AI <reports@resumemate.ai>",
      to: email,
      subject: "Your ResumeMate AI Pro Report",
      text: `Here is your ResumeMate AI Pro Report:\n\n${reportText.slice(0, 50_000)}`,
      html: `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <h1 style="color: #1e40af; font-size: 24px;">Your ResumeMate AI Pro Report</h1>
          <p style="color: #6b7280; font-size: 14px;">Thank you for using ResumeMate AI. Here is your full analysis report.</p>
          <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;" />
          <pre style="white-space: pre-wrap; font-family: monospace; font-size: 13px; color: #374151; background: #f9fafb; padding: 16px; border-radius: 8px;">${escapeHtml(reportText.slice(0, 50_000))}</pre>
          <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;" />
          <p style="color: #9ca3af; font-size: 12px;">Generated by ResumeMate AI. Your resume data was not stored.</p>
        </div>
      `,
    });

    if (error) {
      console.error("[send-report] Resend error:", error);
      return NextResponse.json(
        { error: "Failed to send email. Please try again." },
        { status: 500 }
      );
    }

    console.log("[send-report] Email sent to:", email.replace(/(.{2}).*(@.*)/, "$1***$2"));

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("[send-report] Error:", error instanceof Error ? error.message : "Unknown");
    return NextResponse.json(
      { error: "Failed to send email." },
      { status: 500 }
    );
  }
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
